In [0]:
#Artificial neural network
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
os.chdir('/content/drive/My Drive/Colab Notebooks/MLLab/lab')

In [0]:
df=pd.read_csv("Bank.csv")

In [0]:
#preprocessing
x=df.iloc[:,3:13].values
y=df.iloc[:,13].values

In [8]:
x.shape

(10000, 10)

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [10]:
#Encoding the catogorical variable
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X1=LabelEncoder()
x[:,1]=labelencoder_X1.fit_transform(x[:,1])
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
labelencoder_X2=LabelEncoder()
x[:,2]=labelencoder_X1.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()

In [13]:
x[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [0]:
x=x[:,1:]

In [15]:
x[:,1]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [0]:
#splitiing the dataset into the Training set and test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [0]:
#feautre scaling important for deep learning
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [0]:
X_train.shape

In [0]:
#Part 2
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
#initializing the ANN
classifier=Sequential()

In [0]:
#Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


Instructions for updating:
Colocations handled automatically by placer.


In [0]:
#Adding the second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [0]:
#Adding the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation="sigmoid"))


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [0]:
#compiling the ANN
#optimizer= adma is function that is give u gradient decent approach and it will reduce the error
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [0]:
X_train.shape

(8000, 11)

In [0]:
y_train.shape

(8000,)

In [0]:
#fitting the ANN to the training set
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

Instructions for updating:
Use tf.cast instead.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.4951 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 0s 59us/step - loss: 0.4210 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 60us/step - loss: 0.4111 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 59us/step - loss: 0.4024 - acc: 0.8149
Epoch 5/100
8000/8000 [==============================] - 0s 60us/step - loss: 0.3944 - acc: 0.8280
Epoch 6/100
8000/8000 [==============================] - 0s 59us/step - loss: 0.3877 - acc: 0.8291
Epoch 7/100
8000/8000 [==============================] - 0s 60us/step - loss: 0.3815 - acc: 0.8354
Epoch 8/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.3761 - acc: 0.8425
Epoch 9/100
8000/8000 [==============================] - 1s 67us/step - loss: 0.3721 - acc: 0.8475
Epoch 10/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.3687 - acc: 0.8482
Epoch 11

8000/8000 [==============================] - 0s 59us/step - loss: 0.3403 - acc: 0.8612
Epoch 83/100
8000/8000 [==============================] - 0s 61us/step - loss: 0.3398 - acc: 0.8612
Epoch 84/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3406 - acc: 0.8610
Epoch 85/100
8000/8000 [==============================] - 0s 60us/step - loss: 0.3393 - acc: 0.8624
Epoch 86/100
8000/8000 [==============================] - 0s 58us/step - loss: 0.3395 - acc: 0.8625
Epoch 87/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3395 - acc: 0.8634
Epoch 88/100
8000/8000 [==============================] - 0s 61us/step - loss: 0.3397 - acc: 0.8615
Epoch 89/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3385 - acc: 0.8599
Epoch 90/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3390 - acc: 0.8620
Epoch 91/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3390 - acc: 0.8636
Epoch 92/100


In [0]:
#part 3- making the prediction and evaluating the model
#predicting the test set results
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [0]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [0]:
cm

array([[1516,   79],
       [ 200,  205]], dtype=int64)

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8605